
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Discord webhook for logging
export const DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1367344893948596264/t5NxTsZx_w-WcF7qG80_f1kyRDUN4XM3X8geIykT5nTR6IDL7J__PCyKRBnkT5S3F-dP";

// Function to send logs to Discord
export async function logToDiscord(message: string, type: 'info' | 'warning' | 'error' = 'info') {
  try {
    const colors = {
      info: 3447003,      // Blue
      warning: 16776960,  // Yellow
      error: 15158332     // Red
    };
    
    const payload = {
      username: "Yowx Bot",
      embeds: [{
        title: `${type.toUpperCase()}: Yowx Log`,
        description: message,
        color: colors[type],
        timestamp: new Date().toISOString()
      }]
    };
    
    await fetch(DISCORD_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    });
  } catch (err) {
    console.error("Failed to send Discord log:", err);
  }
}
